name: Build Setup
description: Setup for standard Java builds

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: 'false'
  branch:
    description: 'Branch to checkout'
    required: false
    default: '1.20.1'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.branch == '1.20.1' && '17' || '21' }}

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-write-only: ${{ inputs.update-cache }}
        generate-job-summary: false
        gradle-home-cache-includes: |
          caches
          notifications
          jdks
          wrapper
