name: Build Artifacts on Merge

on:
  push:
    branches: ['1.20.1', '1.21']
    paths-ignore: ['**/*.md, **/*.yml']

concurrency:
  group: auto-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      SNAPSHOT: true
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get Build Setup
        uses: actions/checkout@v4
        with:
          ref: '1.20.1'
          sparse-checkout: '.github'
      - name: Setup Build
        uses: ./.github/actions/build_setup
      - name: Build
        run: ./gradlew build --build-cache
      - name: Publish to Maven
        run: ./gradlew publish --build-cache
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*
          if-no-files-found: error
          retention-days: 90
      - name: Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ./.github/config-latest.json
          fromTag: latest-${{ github.ref_name }}
          toTag: ${{ github.ref }}
          fetchViaCommits: true
          failOnError: false
      - name: Release Latest
        uses: andelf/nightly-release@46e2d5f
        with:
          tag_name: latest-${{ github.ref_name }}
          name: 'GTCEu Modern ${{ github.ref_name }} SNAPSHOT $$'
          prerelease: true
          body: |
            The latest build of GTM for Minecraft ${{ github.ref_name }}.
            Please report any [issues](https://github.com/GregTechCEu/GregTech-Modern/issues)
            ${{ steps.changelog.outputs.changelog }}
          files: build/libs/!(*-@(dev|dev-all|dev-slim|javadoc)).jar