name: Publish on Release

on:
  release:
    types: [released]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outcome }}
    steps:
      - name: Version Check
        id: check
        run: |
          VER=$(./gradlew -q printVersion | awk -F- '{print "v"$2})
          if [[ "$VER" = ${{ github.event.release.tag_name }} ]]; then exit 0; else exit 1; fi

  build:
    needs: check
    if: needs.check.outputs.status == 'success'
    runs-on: ubuntu-latest
    env:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build
        run: ./gradlew build --build-cache

      - name: Publish to Maven
        if: github.event.release.name != 'simulate'
        run: ./gradlew publish --build-cache

      - name: Get Version
        id: ver
        run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT

      - name: Publish Mod
        uses: Kir-Antipov/mc-publish@v3.3.0
        if: github.event.release.name != 'simulate'
        with:
          modrinth-id: 7tG215v7
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 890405
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/!(*-@(dev|dev-all|dev-slim|sources|javadoc|dev-shadow|slim)).jar
            build/libs/*-@(dev|sources|javadoc|dev-shadow|slim).jar

          name: GregTechCEu ${{ steps.ver.outputs.version }}
          version: mc${{ steps.ver.outputs.version }}
          version-type: beta

          loaders: forge
          java: 17
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: Upload to GH Release
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        with:
          files: |
            build/libs/!(*-@(dev|dev-all|dev-slim|sources|javadoc|dev-shadow|slim)).jar
            build/libs/*-@(dev|sources|javadoc|dev-shadow|slim).jar

      # Change release to draft if something failed above
      - name: Edit Failed Release
        if: ${{ failed() }}
        run: |
          gh release edit ${{ github.event.release.tag_name }} --draft=true

      # After release, update gradle.properties
      - name: Bump Version
        if: ${{ success() }}
        run: |
          git switch -c gh/ver-bump
          VER=$(awk '$1 == "mod_version" {print $3}' gradle.properties)
          BUMPED=$(echo $VER | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
          sed -i "s/= ${VER}/= ${BUMPED}/" gradle.properties
          git commit -am "Bump version"
          git push
          gh pr create -B 1.20.1 -H gh/ver-bump --title "Bump version to $BUMPED" --body "Created by GH Workflow"